sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f DockerFile.dev .

script:
  - docker run -e CI=true docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-3"
  bucket_name: "elasticbeanstalk-us-east-1-821664204980"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY